apiVersion: v1
kind: Namespace
metadata:
  name: widgets
---
apiVersion: v1
kind: Secret
metadata:
  name: widgetapi-token
  namespace: widgets
type: Opaque
stringData:
  TOKEN: "TOKEN"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: devex-platform-charts
  namespace: widgets
spec:
  type: oci
  url: oci://ghcr.io/jcvlds/charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: widgetapi
  namespace: widgets
spec:
  releaseName: widgetapi
  interval: 5m
  chart:
    spec:
      chart: widgetapi
      version: "0.1.3"
      sourceRef:
        kind: HelmRepository
        name: devex-platform-charts
        namespace: widgets
  values:
    gateway:
      enabled: true
      host: widgetapi.juancarlosvaldes.com
    persistence:
      storageClassName: "oci-bv"
      size: 1Gi
    config:
      secretName: widgetapi-token
      secretKeyToken: TOKEN
      uploadLimit: 1048576
