apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: metrics-server
  #     namespace: metrics-server
