apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    # server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    email: jcvlds@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare-private-key
    solvers:
      - dns01:
          cloudflare:
            email: jcvlds@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
