apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  type: oci
  url: oci://docker.io/envoyproxy/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 10m
  releaseName: envoy-gateway
  timeout: 5m
  chart:
    spec:
      chart: gateway-helm # envoy-gateway
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy-gateway-system
      interval: 5m
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-http
spec:
  gatewayClassName: envoy
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-test
spec:
  parentRefs:
    - name: envoy-http
  hostnames:
    - "nginx.juancarlosvaldes.com"
  rules:
    - backendRefs:
        - kind: Service
        - name: nginx-test
        - port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
