apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-system
spec:
  interval: 5m
  type: oci
  url: oci://docker.io/envoyproxy/gateway-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 10m
  releaseName: envoy-gateway
  timeout: 5m
  chart:
    spec:
      chart: gateway-helm # envoy-gateway
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway-system # envoy-gateway
        namespace: flux-system
      interval: 5m
