apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway-system
spec:
  interval: 5m
  url: oci://docker.io/envoyproxy/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gateway-helm # envoy-gateway
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway-system # envoy-gateway
      interval: 5m
  releaseName: envoy-gateway-system # envoy-gateway
