apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juancarlosvaldes.com
  namespace: default
spec:
  secretName: juancarlosvaldes.com
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: '*.juancarlosvaldes.com'
  dnsNames:
  - '*.juancarlosvaldes.com'
  - 'juancarlosvaldes.com'
