# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: bitnami-grafana
#   namespace: flux-system
# spec:
#   type: oci
#   interval: 10m
#   url: oci://registry-1.docker.io/bitnamicharts
# ---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 9.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  releaseName: grafana
  values:
    persistence:
      enabled: true
      size: 50Gi

    # adminPassword:

    initChownData:
      enabled: false
      image:
        registry: docker.io
        repository: library/busybox
        tag: "1.31.1"
        sha: ""
        pullPolicy: IfNotPresent
      securityContext:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          add:
            - CHOWN
          drop:
            - ALL

    securityContext:
      fsGroup: 472
      runAsUser: 472 # Optional but good practice, ensure Grafana runs as this user
      runAsGroup: 472 # Optional, fsGroup often suffices for write access
      runAsNonRoot: true

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus:9090
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki-gateway.monitoring.svc.cluster.local:80
            access: proxy
            isDefault: false
          - name: Thanos
            type: prometheus
            access: proxy
            url: http://thanos-query.monitoring.svc.cluster.local:9090
            isDefault: false
            prometheusType: Thanos
            jsonData:
              timeInterval: "5s"
              customQueryParameters: "max_source_resolution=auto"  # optional downsampling hint 

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        kubernetes-cluster:
          gnetId: 7249
          revision: 1
          datasource: Prometheus
        kubernetes-pods:
          gnetId: 6417
          revision: 1
          datasource: Prometheus
        loki-logs:
          gnetId: 13639
          revision: 1
          datasource: Loki
        loki-dashboard:
          gnetId: 13186
          revision: 1
          datasource: Loki
        node-exporter:
          gnetId: 8732
          revision: 1
          datasource: Prometheus

    service:
      type: NodePort
      nodePort: 30080

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
