apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: grafana
    namespace: monitoring
spec:
  interval: 10m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: observability
spec:
  interval: 10m0s
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: 6.30.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    createNamespace: true
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: oci-credentials
      extraArgs:
        - -config.expand-env=true

    loki:
      auth_enabled: false

      memcached:
      chunk_cache:
        enabled: false

      commonConfig:
        path_prefix: /var/loki
        replication_factor: 1

      storage:
        type: 's3'
        bucketNames:
          chunks: 'loki-chunks'
          ruler: 'loki-ruler'
          # Consider removing 'admin' if using OSS Loki
          admin: 'loki-admin'
        s3:
          endpoint: https://idpl1k067soy.compat.objectstorage.us-ashburn-1.oraclecloud.com
          region: 'us-ashburn-1'
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          s3ForcePathStyle: true

      schemaConfig:
      # schema_config:
        configs:
          - from: "2025-06-01" # Consider updating 'from' to a more recent date or the current date for a new setup
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      compactor:
        working_directory: /var/loki/tsdb-compactor
        # shared_store: s3
        compaction_interval: 5m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: s3

      persistence:
        enabled: true
        size: 10Gi
        # storageClassName: "gp2"

      loki:
        ruler:
          storage:
            type: s3
            s3: # Add this section, mirroring the global S3 config
              endpoint: https://idpl1k067soy.compat.objectstorage.us-ashburn-1.oraclecloud.com
              region: 'us-ashburn-1'
              access_key_id: ${AWS_ACCESS_KEY_ID}
              secret_access_key: ${AWS_SECRET_ACCESS_KEY}
              s3ForcePathStyle: true
            # accessKeyIdSecret:
            #   name: aws-credentials
            #   key: access-key-id
            # secretAccessKeySecret:
            #   name: aws-credentials
            #   key: secret-access-key

    chunksCache:
      enabled: false
    memcachedChunks:
      enabled: false
