# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: grafana
#   namespace: monitoring
# spec:
#   interval: 10m0s
#   url: https://grafana.github.io/helm-charts
# ---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 10m0s
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      version: 6.17.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    createNamespace: true
  values:
    config:
      lokiAddress: http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push
      clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push
      
      snippets:
        scrapeConfigs: |
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                separator: /
                regex: (.*)
                target_label: __path__
                replacement: /var/log/pods/*$1/*.log
            pipeline_stages:
              - cri: {}

    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

    tolerations:
      - effect: NoSchedule
        operator: Exists
