apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: monitoring
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: thanos
      version: 16.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: monitoring
      interval: 10m
  releaseName: thanos
  values:
    existingObjstoreSecret: thanos-objstore-secret

    query:
      enabled: true
      replicaCount: 1
      service:
        type: ClusterIP
        port: 9090
      grpcService:
        port: 10901
      dnsDiscovery:
        sidecarsService: prometheus-operated
        sidecarsNamespace: monitoring

    storegateway:
      enabled: true

    compactor:
      enabled: true
      replicaCount: 1
